---
title: "Frequently Asked Questions"
date: "_Last Updated `r Sys.time()`_"
output:   
  html_document:
    highlight: tango
    css: ../css/yeti.css
    theme: yeti
---

----

# Common Error Messages
Taken from: http://blog.revolutionanalytics.com/2015/03/the-most-common-r-error-messages.html

* `could not find function` errors, usually caused by typos or not loading a required package
* `Error in if` errors, caused by non-logical data or missing values passed to R's `if` conditional statement
* `Error in eval` errors, caused by references to objects that don't exist
* `cannot open` errors, caused by attempts to read a file that doesn't exist or can't be accessed
* `no applicable method` errors, caused by using an object-oriented function on a data type it doesn't support
* `subscript out of bounds` errors, caused by trying to access an element or dimension that doesn't exist
* package errors caused by being unable to install, compile or load a package.
    
----

# Where can I get help using R outside of class time? 

### Online
* Chico [R User Group](https://groups.google.com/forum/#!forum/chico-rug) Google email list and discussion board. 
    - Contribute your own solutions and advice as you can. 
* Stack Overflow using the `R` tag https://stackoverflow.com/questions/tagged/r 
    - Both of these are most helpful when you prepare a [minimal working example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) of your problem for the other users. 
* UCLA IDRE https://stats.idre.ucla.edu/r/ 
* Cookbook for R http://www.cookbook-r.com/
* R Examples repository http://dwoll.de/rexrepos/index.html 


### In Person (via Zoom during COVID-19): 

* **Community Coding Sessions** 
Similar to drop in Mathematics tutoring hours, students, staff, faculty, and the public are invited to join our Community Coding sessions. Bring your computer, coding projects, and your questions to this open working environment. Schedule and info found at https://www.csuchico.edu/datascience/community-coding.shtml 
* **Robin Donatello** - Stat professor. Holt 202. rdonatello@csuchico.edu 
    - OH TBD
    - Some community coding sessions. 
* **Edward Roualdes** - Stat professor. Holt 204. eroualdes@csuchico.edu
    - No official OH for AY 2021-22 
* **Kathy Gray** - Stat professor. Holt 108. klgray@csuchico.edu
* **Jane Guo** - Stat professor. Holt 150. jguo2@csuchico.edu
* **Nicholas Lytal** - Stat professor. Holt xxx. nlytal@csuchico.edu
* **Peer Mentors** (possibly paid tutoring, some you can catch in the Math tutoring lab)
    
----

# What other computers on campus have R? 

* All campus computers should have R & R Studio installed on them. 
* Butte 207 & 211 are open computer labs.


    
   
    