---
title: "Course materials"
output:   
  html_document:
    highlight: tango
    css: ../css/yeti.css
    theme: yeti
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(stringr)
library(pander)
library(knitr); library(kableExtra)
opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
options(knitr.kable.NA = '')
```

----

## Assignments

```{r}
f  <- list.files("hw", pattern='*.Rmd')
f <- f[!grepl("solutions", f )]
hw <- data.frame(filenames = paste0('hw/', f ))

out.hw <- hw %>% mutate(name = gsub("hw/|.Rmd",  "", filenames), 
                        link = sprintf("[%s](%s)",name, filenames))

```

```{r}
kable(t(out.hw$link), align='c') %>% 
  column_spec (1:4,border_left = T, border_right = T) %>%
  kable_classic(full_width = F, html_font = "Courier New", font_size = 25, position = "left")
```


```{r}

# HTML files
file.names <- list.files("notes", pattern='.html')
html.path  <- paste0("notes/", file.names)
html.files <- data.frame(
  name =  gsub(".html", "", file.names),
  idx = str_extract(html.path, "\\d{2}"), 
  HTML = sprintf("[HTML](%s)", html.path)
  )

# PDF files
pdf.path  <- paste0("notes/", list.files("notes", pattern='.pdf'))
pdf.files <- data.frame(idx = str_extract(pdf.path, "\\d{2}"), 
                        PDF = sprintf("[PDF](%s)", pdf.path)
                         ) %>% filter(!is.na(idx))

# helper RMD files
note.rmd.files <- list.files("notes", pattern='notes')
helper.files <- data.frame(idx = str_extract(note.rmd.files, "\\d{2}"), 
                           `Helper Files` = sprintf("[RMD](%s)", note.rmd.files)
                           )

display <- full_join(html.files, pdf.files) %>% 
  full_join(helper.files) %>% 
  select(-idx) %>%
  rename(`Lesson Name` = name, `Helper File` = Helper.Files)
```

<br>

## Lecture notes
Most notes and slides are available in both HTML and PDF formats. For some lessons R Markdown "fill in the blank" helper notes are also available. 
To download RMD files, right click and "save as". Do not open in a browser then save. 


```{r}
kable(display, align='lccc') %>% 
  kable_styling(full_width = F, bootstrap_options = c("striped", "hover"), 
                html_font = "Courier New", font_size = 15, position = "left")
```


## Video Recordings
Coming soon


