---
title: "Syllabus"
date: last-modified
toc: true
format: 
  html: default
  pdf: default
---


# Course Description
This course is designed as a primer to get the complete novice up and running with the basic knowledge of how to use the statistical programming language R in an environment that emphasizes reproducible research and literate programming for data analysis. The target audience is anyone who wants to do their own data analysis. The course will culminate with a peer-evaluated exploratory data analysis on either a pre-specified data set or your data set of choice.


# Logistics
<!-- updateme -->

* **Course Website:** https://norcalbiostat.github.io/MATH130/
* **Prerequisites:** Basic computer literacy
* **Workshop style:** This workshop style class runs for 5 weeks only. See expectations for time commitment during these 5 weeks below.
* **Discord Server:** https://discord.gg/ck497bJty5

|                        |        Section 01       |
|:-----------------------|:-----------------------:|
| **Meeting Days**       | 08/25/25 - 09/26/25     |
| **Meeting Times**      | MWF 9-10am          |
| **Meeting Location**   | Holt Hall 257         |
| **Instructor**         | Robin Donatello             |
| **Office Location**    | Holt 202                |
| **E-mail**             | rdonatello@csuchico.edu     |

<!-- |                        |        Section 01       | -->
<!-- |:-----------------------|:-----------------------:| -->
<!-- | **Meeting Days**       | 01/21/25 - 02/21/25     | -->
<!-- | **Meeting Times**      | (Asynchronous)          | -->
<!-- | **Meeting Location**   | (Asynchronous)          | -->
<!-- | **Instructor**         | Edward Roualdes              | -->
<!-- | **Office Location**    | Holt 204                | -->
<!-- | **E-mail**             | eroualdes@csuchico.edu     | -->


<!-- |                        |        Section 01       |  -->
<!-- |:-----------------------|:-----------------------:| -->
<!-- | **Meeting Days**       | 08/26/24 - 09/27/24     |  -->
<!-- | **Meeting Times**      |  MWF 9:00 am - 9:50 am  |   -->
<!-- | **Meeting Location**   |     Holt 185      |   -->
<!-- | **Instructor**         | Jing (Jane) Guo              |   -->
<!-- | **Office Location**    | Holt 150                |   -->
<!-- | **E-mail**             | jguo2@csuchico.edu     |   -->



## Course structure
<!-- updateme -->

<!-- **Asynchronous**: this class is fully online and asynchronous. -->

<!-- There are no set meeting times, but assignments still have due dates. Lectures are all pre-recorded and linked from the class website. Students work through the material and complete assignments at their own pace. See [[this page]](notes/01e_async_protocol.html) for more details on the course format. -->

This is a flipped classroom. Before set meeting times, students are expected to watch the video lectures. Lectures are all pre-recorded and linked from the class website. During class meeting time, the instructor will provide brief comments, feedback and guidance, then students complete assignments at their own pace and ask the instructor questions when needed. Collaboration with other classmates is encouraged

## Office Hours
<!-- updateme -->

For the first five weeks of the semester (8/25/2025 - 2/21/2025), my office hours will be in the [Meriam Library Innovation Lab](https://library.csuchico.edu/innovation-lab):

* Mondays 1pm - 2.30pm
* Tuesdays 1pm - 2.30pm
* Thursdays 11am - 11.50am
* Fridays 2pm - 3.45pm

If none of those times work for you, [use this link](https://dr-donatello.youcanbook.me/) to book an appointment with me.

## Canvas Usage
<!-- updateme -->

All learning content is provided on the course website. 
Canvas will be used to submit homework, grades, and friendly 
reminders to the class.

## Student Support

### Discord
To facilitate peer to peer and effective instructor to peer assistance Discord will be used for discussion and questions outside of class. This server hosts students across multiple Statistics and Data Science classes, with a specific channel for all sections of Math 130.

1. Click this link to join the server: https://discord.gg/ck497bJty5
2. Verify your email and agree to the rules and code of conduct. This helps create a safe learning environment.
3. Go to the `#class-selection` text channel in the left sidebar, and click the RStudio icon emoji under the any post to self-assign you to the Math-130 role.  This will let you see and access the class channels.
4. Post a question or 10 to the Math-130 channel.

### Community Coding.
Similar to drop in Mathematics tutoring hours, students, staff, faculty, and the public are invited to join our Community Coding sessions. Bring your computer, coding projects, and your questions to this open working environment. For asynchronous sections, this is the best way to get direct instructor assistance.

* Schedule and info found at https://datascience.csuchico.edu/communitycoding

# Learning Outcomes
By the end of the course, students will be able to

* Import data into R from external files such as text files and spreadsheets.
* Calculate summary statistics.
* Create new variables using different data types.
* Perform data management techniques such as filtering, grouping, summarizing.
* Create informative data visualizations and tables.
* Create a reproducible research document.
* Conduct an exploratory data analysis in a reproducible manner.

# Schedule of Topics
The general outline of topics is listed below. A detailed most up to date schedule can be found on the course website.

* Week 1
    - Introduction to the R language and the R Studio Environment
    - Conducting reproducible research with R Markdown
* Week 2
    - How to use functions to get things done
    - Introduction to data processing
* Week 3
    - Univariate Data Visualization using base, and `ggplot2` graphics
    - Streamlined Data processing and Aggregation with `dplyr`
* Week 4
    - Bivariate and Multivariate Data Visualization using `ggplot2`
    - Importing data into R from external files
* Week 5: Exploratory Data Analysis (individual project)


# Required Materials

* A reliable laptop, chromebook, tablet that can use a browser to access the internet.
* Reliable internet connection while on and off campus.

#### Software
If you have your own PC/Mac/*nix computer, you are advised to install  R and R Studio on your personal computer. That way you can take what you've learned in this class and apply it to other classes. Both are free. Walk through installation instructions can be found here: https://norcalbiostat.netlify.com/post/software-overview/

* R version 4.4.1 or later. Download from https://cran.r-project.org/
* R Studio version 2024.12.0 or later. Download the desktop version from https://www.rstudio.com/products/rstudio/download/#download

Students who do not have a computer that they install programs on (i.e. a iPad or Chromebook) can use the [Wildcat virtual lab](https://support.csuchico.edu/TDClient/1984/Portal/KB/ArticleDet?ID=112333), or sign up for R Studio Cloud (https://rstudio.cloud/). The free or $5/month plan should be sufficient.


# Time Commitment

> For all CSU degree programs and courses bearing academic credit, the "credit hour" is defined as ... not less than one hour of classroom or direct faculty instruction and a minimum of two hours of out-of-class student work each week for approximately fifteen weeks for one semester or trimester hour of credit.

This adds up to 15 hours in class, and 30 hours outside of class during these 5 weeks. That's 3 hours in class, and 10 hours of homework per week. If you are new to programming and unfamiliar with computers, you may end up taking the entire time. Be sure to schedule sufficient time during week 5 to work on the project.

You will get out of this class what you put into it. Recall this is just a co-curriculuar or supplemental basic introductory class. You will not learn everything there is to know about R, nor likely not feel proficient by the time you are done. But you will be solidly on the path where you can continue to learn and improve.

# Grading
<!-- updateme -->

Credit / No Credit. There are 100 points available in this course. You must earn **75** points to receive credit for the course. 

* Assignments: 4 @ 10 pts each.
* Fill out course notes: 7 @ 5 pts each
* Project:
    - Exploratory Data Analysis (20 pts)
    - Peer Review (5 pts)
    
Assignments are due after each week, Sunday by midnight. Follow along lecture
notes are due on Wednesday & Friday - generally 1-2 days after that lesson is complete. 

Assignments are submitted through Canvas. 

Any assignment can be submitted as late within the week after it is due
for a one point deduction.


<!-- Assignments are submit by uploading the appropriate files to a Google -->
<!-- Drive shared notebook, which I will create for you.  The shared Google -->
<!-- Drive folder will be named MATH 130 Assignments for -->
<!-- [student-username], where [student-username] is your student username. -->
<!-- Only, specifically, you, me, and the course graders will have access -->
<!-- to this folder. -->

----

# Class Policies and statements

## Everyone is welcome here

It is our intent that students from all diverse backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength and benefit. It is our intent to present materials and activities that are respectful of diversity: gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, and culture. Your suggestions are encouraged and appreciated. Please let us know ways to improve the effectiveness of the course for you personally, or for other students or student groups.

We would like to create a learning environment that supports a diversity of thoughts, perspectives and experiences, and honors your identities (including race, gender, class, sexuality, religion, ability, etc.) To help accomplish this:

* If you have a name and/or set of pronouns that differ from those that appear in your official Chico records, please let us know!
* If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with us. We want to be a resource for you. Remember that you can also submit anonymous feedback (which may lead to a general announcement to the class, if necessary to address the concerns).
* If you prefer to speak with someone outside of the course, the Office of Diversity and Inclusion is here to assist. Their number is 530-898-4764, and email diversityoffice@csuchico.edu
* We (like many people) are still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it. (Again, anonymous feedback is always an option).


_Adapted from [Monica Linden at Brown University](https://www.brown.edu/sheridan/teaching-learning-resources/inclusive-teaching/statements)_.

We acknowledge and are mindful that Chico State stands on lands that were originally occupied by the first people of this area, the Mechoopda, and we recognize their distinctive spiritual relationship with this land, the flora, the fauna, and the waters that run through campus. We are humbled that our campus resides upon sacred lands that since time immemorial have sustained the Mechoopda people and continue to do so today.

----

# University Policies and Campus Resources

### Adding and Dropping the course
This course only runs for a few weeks and all materials are available on the course website. It will be difficult to get caught up if you add the class after the first week. The last day to add or drop classes without special permission by the instructor is 9/6/25. No adds or drops are allowed after 9/6/25 without a serious and compelling reason approved by the instructor, department chair, and college dean.

### Academic Integrity
Students are expected to be familiar with the University’s Academic Integrity Policy. Your own commitment to learning, as evidenced by your enrollment at California State University, Chico, and the University’s Academic Integrity Policy requires you to be honest in all your academic course work. Faculty members are required to report all infractions to the Office of Student Judicial Affairs. The policy on academic integrity and other resources related to student conduct can be found on the Student Judicial Affairs web site at http://www.csuchico.edu/sjd/integrity.shtml.

### AI and ChatGPT Policy
AI writing tools are not permitted for any stage or phase of work in this class. If you use these tools, your actions will be considered academically dishonest, and a violation of Chico State's Integrity Policy and you may be reported to the Office of Students Rights and Responsibilities.

### IT Support Services

Computer labs for student use are located in the Innovation Lab 2nd floor, and on the first and fourth floor of the Meriam Library, Room 116 and 450,Tehama Hall Room 131, and the Bell Memorial Union (BMU) basement. You can get help using your computer from IT Support Services; contact them through the ITSS web site at http://www.csuchico.edu/itss. Additional labs may be available to students in your department or college.



### Americans with Disabilities Act
If you need course adaptations or accommodations because of a disability or chronic illness,  or if you need to make special arrangements in case the building must be evacuated, please make an appointment with me as soon as possible, or see me during office hours. Please also contact Accessibility Resource Center (ARC) as they are the designated department responsible for approving and coordinating reasonable accommodations and services for students with disabilities. ARC will help you understand your rights and responsibilities under the Americans with Disabilities Act and provide you further assistance with requesting and arranging accommodations.

Accessibility Resource Center
530-898-5959
Student Services Center 170
arcdept@csuchico.edu
http://www.csuchico.edu/arc



### Chico State Basic Needs Project
The **Hungry Wildcat Food Pantry** provides supplemental food, fresh produce, CalFresh application assistance and basic needs referral services for students experiencing food and housing insecurity.

All students are welcomed to visit the Pantry located in the Student Service Center 196. Check the website for a location map and for the most up to date information on open hours: https://www.csuchico.edu/basic-needs/pantry.shtml .


## Confidentiality and Mandatory Reporting
As an instructor, one of my responsibilities is to help create a safe learning environment on our campus. I also have a mandatory reporting responsibility related to my role as a your instructor. I am required to share information regarding sexual misconduct with the University. Students may speak to someone confidentially by contacting the Counseling and Wellness Center (898-6345) or Safe Place (898-3030). Information on campus reporting obligations and other Title IX related resources are available here: www.csuchico.edu/title-ix.
